# Hermes Company OS gateway operations
# Generated by the dashboard. Review before running.
# This script contains no Slack tokens, Telegram bot tokens, or provider keys.

param(
  [switch]$CheckCommands,
  [switch]$Setup,
  [switch]$Start,
  [switch]$InstallService,
  [string]$DashboardBaseUrl = "http://127.0.0.1:8002",
  [switch]$PostDashboardStatus
)

$ErrorActionPreference = "Stop"

if (-not ($CheckCommands -or $Setup -or $Start -or $InstallService)) {
  $CheckCommands = $true
}

$Profiles = @(
  [pscustomobject]@{
    Id = "chief-of-staff"
    Name = "Chief of Staff"
    Command = "chief-of-staff"
  }
  [pscustomobject]@{
    Id = "product-manager"
    Name = "Product Manager"
    Command = "product-manager"
  }
  [pscustomobject]@{
    Id = "research-agent"
    Name = "Research Agent"
    Command = "research-agent"
  }
  [pscustomobject]@{
    Id = "engineering-manager"
    Name = "Engineering Manager"
    Command = "engineering-manager"
  }
  [pscustomobject]@{
    Id = "marketing-agent"
    Name = "Marketing Agent"
    Command = "marketing-agent"
  }
  [pscustomobject]@{
    Id = "qa-critic"
    Name = "QA / Critic"
    Command = "qa-critic"
  }
  [pscustomobject]@{
    Id = "backend-engineer"
    Name = "Backend Engineer"
    Command = "backend-engineer"
  }
  [pscustomobject]@{
    Id = "frontend-engineer"
    Name = "Frontend Engineer"
    Command = "frontend-engineer"
  }
  [pscustomobject]@{
    Id = "cloud-infra-agent"
    Name = "Cloud Infrastructure Agent"
    Command = "cloud-infra-agent"
  }
  [pscustomobject]@{
    Id = "test-automation-agent"
    Name = "Test Automation Agent"
    Command = "test-automation-agent"
  }
)

function Get-CommandName {
  param([string]$CommandLine)
  return ($CommandLine -split "\s+")[0]
}

function Invoke-GatewayAction {
  param(
    [pscustomobject]$Profile,
    [string]$Action
  )
  $commandLine = "$($Profile.Command) gateway $Action"
  Write-Host ""
  Write-Host "==> $($Profile.Name): $commandLine"
  Invoke-Expression $commandLine
}

function Post-MessagingGatewayStatus {
  param(
    [pscustomobject]$Profile,
    [string]$Action
  )
  $checkId = "$($Profile.Id)-slack-gateway"
  $uri = "$DashboardBaseUrl/setup/messaging-checks/$checkId"
  $body = @{
    status = "loaded"
    evidence = "Gateway operations runner completed gateway $Action for $($Profile.Name)."
  }
  try {
    Invoke-WebRequest `
      -UseBasicParsing `
      -Method Post `
      -Uri $uri `
      -ContentType "application/x-www-form-urlencoded" `
      -Body $body | Out-Null
    Write-Host "DASHBOARD loaded $checkId"
  } catch {
    Write-Host "DASHBOARD skipped ${checkId}: $($_.Exception.Message)"
  }
}

if ($CheckCommands) {
  foreach ($profile in $Profiles) {
    $commandName = Get-CommandName $profile.Command
    if (Get-Command $commandName -ErrorAction SilentlyContinue) {
      Write-Host "FOUND   $($profile.Id): $commandName"
    } else {
      Write-Host "MISSING $($profile.Id): $commandName"
    }
  }
}

if ($Setup) {
  foreach ($profile in $Profiles) {
    Invoke-GatewayAction $profile "setup"
    if ($PostDashboardStatus) {
      Post-MessagingGatewayStatus $profile "setup"
    }
  }
}

if ($InstallService) {
  foreach ($profile in $Profiles) {
    Invoke-GatewayAction $profile "install"
    if ($PostDashboardStatus) {
      Post-MessagingGatewayStatus $profile "install"
    }
  }
}

if ($Start) {
  Write-Host "Foreground gateway start may block this terminal."
  Write-Host "Use one terminal per profile if needed."
  foreach ($profile in $Profiles) {
    Invoke-GatewayAction $profile "start"
    if ($PostDashboardStatus) {
      Post-MessagingGatewayStatus $profile "start"
    }
  }
}

Write-Host ""
Write-Host "Gateway operation finished. Complete /setup#messaging-verification next."
