# Hermes Company OS live starter profile assets
# Generated by the dashboard. Review before running.
# This writes only non-secret starter files. It does not read or write .env values.

param(
  [string]$DashboardBaseUrl = "http://127.0.0.1:8002",
  [string]$HermesHome = $(if ($env:HERMES_HOME) { $env:HERMES_HOME } elseif ($env:LOCALAPPDATA) { Join-Path $env:LOCALAPPDATA "hermes" } else { Join-Path $env:USERPROFILE ".hermes" }),
  [string]$ProfileRoot = (Join-Path $HermesHome "profiles")
)

$ErrorActionPreference = "Stop"

$Profiles = @(
  [pscustomobject]@{
    Id = "chief-of-staff"
    Name = "Chief of Staff"
  }
  [pscustomobject]@{
    Id = "product-manager"
    Name = "Product Manager"
  }
  [pscustomobject]@{
    Id = "research-agent"
    Name = "Research Agent"
  }
  [pscustomobject]@{
    Id = "engineering-manager"
    Name = "Engineering Manager"
  }
  [pscustomobject]@{
    Id = "marketing-agent"
    Name = "Marketing Agent"
  }
  [pscustomobject]@{
    Id = "qa-critic"
    Name = "QA / Critic"
  }
  [pscustomobject]@{
    Id = "backend-engineer"
    Name = "Backend Engineer"
  }
  [pscustomobject]@{
    Id = "frontend-engineer"
    Name = "Frontend Engineer"
  }
  [pscustomobject]@{
    Id = "cloud-infra-agent"
    Name = "Cloud Infrastructure Agent"
  }
  [pscustomobject]@{
    Id = "test-automation-agent"
    Name = "Test Automation Agent"
  }
)

foreach ($profile in $Profiles) {
  $profilePath = Join-Path $ProfileRoot $profile.Id
  if (-not (Test-Path -LiteralPath $profilePath)) {
    throw (
      "Missing Hermes profile directory: $($profile.Id). " +
      "Run /setup/profile-apply/$($profile.Id).ps1 first."
    )
  }

  Invoke-WebRequest -UseBasicParsing `
    -Uri "$DashboardBaseUrl/setup/profile-live-config/$($profile.Id).yaml" `
    -OutFile (Join-Path $profilePath "config.yaml")
  Invoke-WebRequest -UseBasicParsing `
    -Uri "$DashboardBaseUrl/setup/profile-live-context/$($profile.Id).md" `
    -OutFile (Join-Path $profilePath "COMPANY_CONTEXT.md")
  Invoke-WebRequest -UseBasicParsing `
    -Uri "$DashboardBaseUrl/setup/profile-live-prompts/$($profile.Id).md" `
    -OutFile (Join-Path $profilePath "PROMPTS.md")
  Invoke-WebRequest -UseBasicParsing `
    -Uri "$DashboardBaseUrl/setup/profile-live-rules/$($profile.Id).md" `
    -OutFile (Join-Path $profilePath "OPERATING_RULES.md")

  Write-Host "WROTE $($profile.Id) config.yaml COMPANY_CONTEXT.md PROMPTS.md OPERATING_RULES.md"
}

Write-Host ""
Write-Host "Live starter assets applied. Credential files were not touched."
