# Hermes Company OS external secret audit
# Generated by the dashboard. Review before running.
# This script checks key presence only; it does not print credential values.

param(
  [string]$DashboardBaseUrl = "http://127.0.0.1:8002",
  [string]$HermesHome = $(if ($env:HERMES_HOME) { $env:HERMES_HOME } elseif ($env:LOCALAPPDATA) { Join-Path $env:LOCALAPPDATA "hermes" } else { Join-Path $env:USERPROFILE ".hermes" }),
  [string]$ProfileRoot = (Join-Path $HermesHome "profiles"),
  [switch]$PostDashboardStatus,
  [switch]$AuditLlm
)

$ErrorActionPreference = "Stop"

$Requirements = @(
  [pscustomobject]@{
    Id = "backend-engineer-slack-app-token"
    Profile = "backend-engineer"
    Category = "slack"
    Label = "Backend Engineer Slack app token"
    Keys = @("SLACK_APP_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "backend-engineer-slack-bot-token"
    Profile = "backend-engineer"
    Category = "slack"
    Label = "Backend Engineer Slack bot token"
    Keys = @("SLACK_BOT_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "chief-of-staff-slack-app-token"
    Profile = "chief-of-staff"
    Category = "slack"
    Label = "Chief of Staff Slack app token"
    Keys = @("SLACK_APP_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "chief-of-staff-slack-bot-token"
    Profile = "chief-of-staff"
    Category = "slack"
    Label = "Chief of Staff Slack bot token"
    Keys = @("SLACK_BOT_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "cloud-infra-agent-slack-app-token"
    Profile = "cloud-infra-agent"
    Category = "slack"
    Label = "Cloud Infrastructure Agent Slack app token"
    Keys = @("SLACK_APP_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "cloud-infra-agent-slack-bot-token"
    Profile = "cloud-infra-agent"
    Category = "slack"
    Label = "Cloud Infrastructure Agent Slack bot token"
    Keys = @("SLACK_BOT_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "engineering-manager-slack-app-token"
    Profile = "engineering-manager"
    Category = "slack"
    Label = "Engineering Manager Slack app token"
    Keys = @("SLACK_APP_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "engineering-manager-slack-bot-token"
    Profile = "engineering-manager"
    Category = "slack"
    Label = "Engineering Manager Slack bot token"
    Keys = @("SLACK_BOT_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "frontend-engineer-slack-app-token"
    Profile = "frontend-engineer"
    Category = "slack"
    Label = "Frontend Engineer Slack app token"
    Keys = @("SLACK_APP_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "frontend-engineer-slack-bot-token"
    Profile = "frontend-engineer"
    Category = "slack"
    Label = "Frontend Engineer Slack bot token"
    Keys = @("SLACK_BOT_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "marketing-agent-slack-app-token"
    Profile = "marketing-agent"
    Category = "slack"
    Label = "Marketing Agent Slack app token"
    Keys = @("SLACK_APP_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "marketing-agent-slack-bot-token"
    Profile = "marketing-agent"
    Category = "slack"
    Label = "Marketing Agent Slack bot token"
    Keys = @("SLACK_BOT_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "product-manager-slack-app-token"
    Profile = "product-manager"
    Category = "slack"
    Label = "Product Manager Slack app token"
    Keys = @("SLACK_APP_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "product-manager-slack-bot-token"
    Profile = "product-manager"
    Category = "slack"
    Label = "Product Manager Slack bot token"
    Keys = @("SLACK_BOT_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "qa-critic-slack-app-token"
    Profile = "qa-critic"
    Category = "slack"
    Label = "QA / Critic Slack app token"
    Keys = @("SLACK_APP_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "qa-critic-slack-bot-token"
    Profile = "qa-critic"
    Category = "slack"
    Label = "QA / Critic Slack bot token"
    Keys = @("SLACK_BOT_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "research-agent-slack-app-token"
    Profile = "research-agent"
    Category = "slack"
    Label = "Research Agent Slack app token"
    Keys = @("SLACK_APP_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "research-agent-slack-bot-token"
    Profile = "research-agent"
    Category = "slack"
    Label = "Research Agent Slack bot token"
    Keys = @("SLACK_BOT_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "test-automation-agent-slack-app-token"
    Profile = "test-automation-agent"
    Category = "slack"
    Label = "Test Automation Agent Slack app token"
    Keys = @("SLACK_APP_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "test-automation-agent-slack-bot-token"
    Profile = "test-automation-agent"
    Category = "slack"
    Label = "Test Automation Agent Slack bot token"
    Keys = @("SLACK_BOT_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "chief-of-staff-telegram-bot-token"
    Profile = "chief-of-staff"
    Category = "telegram"
    Label = "Chief of Staff Telegram bot token"
    Keys = @("TELEGRAM_BOT_TOKEN")
    AuditLast = $false
  }
  [pscustomobject]@{
    Id = "backend-engineer-llm-provider-credential"
    Profile = "backend-engineer"
    Category = "llm"
    Label = "Backend Engineer LLM provider credential"
    Keys = @("OPENROUTER_API_KEY")
    AuditLast = $true
  }
  [pscustomobject]@{
    Id = "chief-of-staff-llm-provider-credential"
    Profile = "chief-of-staff"
    Category = "llm"
    Label = "Chief of Staff LLM provider credential"
    Keys = @("OPENROUTER_API_KEY")
    AuditLast = $true
  }
  [pscustomobject]@{
    Id = "cloud-infra-agent-llm-provider-credential"
    Profile = "cloud-infra-agent"
    Category = "llm"
    Label = "Cloud Infrastructure Agent LLM provider credential"
    Keys = @("OPENROUTER_API_KEY")
    AuditLast = $true
  }
  [pscustomobject]@{
    Id = "engineering-manager-llm-provider-credential"
    Profile = "engineering-manager"
    Category = "llm"
    Label = "Engineering Manager LLM provider credential"
    Keys = @("OPENROUTER_API_KEY")
    AuditLast = $true
  }
  [pscustomobject]@{
    Id = "frontend-engineer-llm-provider-credential"
    Profile = "frontend-engineer"
    Category = "llm"
    Label = "Frontend Engineer LLM provider credential"
    Keys = @("OPENROUTER_API_KEY")
    AuditLast = $true
  }
  [pscustomobject]@{
    Id = "marketing-agent-llm-provider-credential"
    Profile = "marketing-agent"
    Category = "llm"
    Label = "Marketing Agent LLM provider credential"
    Keys = @("OPENROUTER_API_KEY")
    AuditLast = $true
  }
  [pscustomobject]@{
    Id = "product-manager-llm-provider-credential"
    Profile = "product-manager"
    Category = "llm"
    Label = "Product Manager LLM provider credential"
    Keys = @("OPENROUTER_API_KEY")
    AuditLast = $true
  }
  [pscustomobject]@{
    Id = "qa-critic-llm-provider-credential"
    Profile = "qa-critic"
    Category = "llm"
    Label = "QA / Critic LLM provider credential"
    Keys = @("OPENROUTER_API_KEY")
    AuditLast = $true
  }
  [pscustomobject]@{
    Id = "research-agent-llm-provider-credential"
    Profile = "research-agent"
    Category = "llm"
    Label = "Research Agent LLM provider credential"
    Keys = @("OPENROUTER_API_KEY")
    AuditLast = $true
  }
  [pscustomobject]@{
    Id = "test-automation-agent-llm-provider-credential"
    Profile = "test-automation-agent"
    Category = "llm"
    Label = "Test Automation Agent LLM provider credential"
    Keys = @("OPENROUTER_API_KEY")
    AuditLast = $true
  }
)

function Test-ProfileEnvKeys {
  param(
    [string]$Profile,
    [string[]]$Keys
  )
  $envPath = Join-Path (Join-Path $ProfileRoot $Profile) ".env"
  $loaded = @()
  $missing = @()
  if (-not (Test-Path -LiteralPath $envPath)) {
    return [pscustomobject]@{ EnvPath = $envPath; Loaded = $loaded; Missing = $Keys }
  }
  $lines = Get-Content -LiteralPath $envPath
  foreach ($key in $Keys) {
    $found = $false
    foreach ($line in $lines) {
      $pattern = "^\s*" + [regex]::Escape($key) + "\s*=\s*(.*)$"
      if ($line -match $pattern) {
        $value = $Matches[1].Trim().Trim('"').Trim("'")
        if ($value -and $value -notmatch "^(REPLACE|TODO|CHANGE_ME|PLACEHOLDER)") {
          $found = $true
        }
      }
    }
    if ($found) {
      $loaded += $key
    } else {
      $missing += $key
    }
  }
  [pscustomobject]@{ EnvPath = $envPath; Loaded = $loaded; Missing = $missing }
}

function Post-LoadedStatus {
  param([string]$RequirementId)
  $uri = "$DashboardBaseUrl/setup/secret-requirements/$RequirementId"
  $body = @{
    status = "loaded"
    notes = "Local audit found required key names in the Hermes profile env file."
  }
  Invoke-WebRequest -UseBasicParsing -Method Post -Uri $uri -Body $body | Out-Null
}

foreach ($requirement in $Requirements) {
  if ($requirement.AuditLast -and -not $AuditLlm) {
    Write-Host "DEFERRED $($requirement.Label) (rerun with -AuditLlm)"
    continue
  }
  $result = Test-ProfileEnvKeys -Profile $requirement.Profile -Keys $requirement.Keys
  if ($result.Missing.Count -eq 0) {
    Write-Host "LOADED   $($requirement.Label)"
    if ($PostDashboardStatus) {
      Post-LoadedStatus -RequirementId $requirement.Id
    }
  } else {
    Write-Host "MISSING  $($requirement.Label): $($result.Missing -join ', ')"
  }
}

Write-Host ""
Write-Host "Secret audit finished. Values were not printed or sent to the dashboard."
