# Hermes Company OS Slack provisioning runner
# Generated by the dashboard. Review before running.
# Default mode is dry run. No token values are printed.

param(
  [switch]$CreateChannels,
  [switch]$InviteBots,
  [switch]$Execute,
  [string]$TokenEnvironmentKey = "HERMES_SLACK_ADMIN_TOKEN",
  [string]$BotUserMapPath = ".\slack-bot-user-map.json",
  [string]$DashboardBaseUrl = "http://127.0.0.1:8002",
  [switch]$PostDashboardInputs
)

$ErrorActionPreference = "Stop"

$Channels = @(
  [pscustomobject]@{
    Name = "#founder-command"
    ApiName = "founder-command"
    ChannelId = "C0BCFL8RE87"
    InputKey = "slack_channel_founder_command"
    Required = $true
    Purpose = "Founder approvals, Chief of Staff coordination, and command intake."
    Bots = @(
      [pscustomobject]@{
        ProfileId = "chief-of-staff"
        BotDisplayName = "Hermes Chief of Staff"
        HermesCommand = "chief-of-staff"
      }
    )
  }
  [pscustomobject]@{
    Name = "#agent-standup"
    ApiName = "agent-standup"
    ChannelId = ""
    InputKey = "slack_channel_agent_standup"
    Required = $true
    Purpose = "9 AM and 3 PM ET operating summaries and cross-profile status."
    Bots = @(
      [pscustomobject]@{
        ProfileId = "chief-of-staff"
        BotDisplayName = "Hermes Chief of Staff"
        HermesCommand = "chief-of-staff"
      }
      [pscustomobject]@{
        ProfileId = "product-manager"
        BotDisplayName = "Hermes Product Manager"
        HermesCommand = "product-manager"
      }
      [pscustomobject]@{
        ProfileId = "research-agent"
        BotDisplayName = "Hermes Research Agent"
        HermesCommand = "research-agent"
      }
      [pscustomobject]@{
        ProfileId = "engineering-manager"
        BotDisplayName = "Hermes Engineering Manager"
        HermesCommand = "engineering-manager"
      }
      [pscustomobject]@{
        ProfileId = "marketing-agent"
        BotDisplayName = "Hermes Marketing Agent"
        HermesCommand = "marketing-agent"
      }
      [pscustomobject]@{
        ProfileId = "qa-critic"
        BotDisplayName = "Hermes QA Critic"
        HermesCommand = "qa-critic"
      }
      [pscustomobject]@{
        ProfileId = "backend-engineer"
        BotDisplayName = "Hermes Backend Engineer"
        HermesCommand = "backend-engineer"
      }
      [pscustomobject]@{
        ProfileId = "frontend-engineer"
        BotDisplayName = "Hermes Frontend Engineer"
        HermesCommand = "frontend-engineer"
      }
      [pscustomobject]@{
        ProfileId = "cloud-infra-agent"
        BotDisplayName = "Hermes Cloud Infrastructure Agent"
        HermesCommand = "cloud-infra-agent"
      }
      [pscustomobject]@{
        ProfileId = "test-automation-agent"
        BotDisplayName = "Hermes Test Automation Agent"
        HermesCommand = "test-automation-agent"
      }
    )
  }
  [pscustomobject]@{
    Name = "#product"
    ApiName = "product"
    ChannelId = ""
    InputKey = "slack_channel_product"
    Required = $true
    Purpose = "Product decisions, PRDs, workflow scope, and tradeoffs."
    Bots = @(
      [pscustomobject]@{
        ProfileId = "chief-of-staff"
        BotDisplayName = "Hermes Chief of Staff"
        HermesCommand = "chief-of-staff"
      }
      [pscustomobject]@{
        ProfileId = "product-manager"
        BotDisplayName = "Hermes Product Manager"
        HermesCommand = "product-manager"
      }
    )
  }
  [pscustomobject]@{
    Name = "#research"
    ApiName = "research"
    ChannelId = ""
    InputKey = "slack_channel_research"
    Required = $true
    Purpose = "Market, customer, competitor, and technical research."
    Bots = @(
      [pscustomobject]@{
        ProfileId = "chief-of-staff"
        BotDisplayName = "Hermes Chief of Staff"
        HermesCommand = "chief-of-staff"
      }
      [pscustomobject]@{
        ProfileId = "research-agent"
        BotDisplayName = "Hermes Research Agent"
        HermesCommand = "research-agent"
      }
    )
  }
  [pscustomobject]@{
    Name = "#engineering"
    ApiName = "engineering"
    ChannelId = ""
    InputKey = "slack_channel_engineering"
    Required = $true
    Purpose = "Architecture, AWS, distributed systems, implementation planning, and tests."
    Bots = @(
      [pscustomobject]@{
        ProfileId = "chief-of-staff"
        BotDisplayName = "Hermes Chief of Staff"
        HermesCommand = "chief-of-staff"
      }
      [pscustomobject]@{
        ProfileId = "engineering-manager"
        BotDisplayName = "Hermes Engineering Manager"
        HermesCommand = "engineering-manager"
      }
      [pscustomobject]@{
        ProfileId = "backend-engineer"
        BotDisplayName = "Hermes Backend Engineer"
        HermesCommand = "backend-engineer"
      }
      [pscustomobject]@{
        ProfileId = "frontend-engineer"
        BotDisplayName = "Hermes Frontend Engineer"
        HermesCommand = "frontend-engineer"
      }
      [pscustomobject]@{
        ProfileId = "cloud-infra-agent"
        BotDisplayName = "Hermes Cloud Infrastructure Agent"
        HermesCommand = "cloud-infra-agent"
      }
      [pscustomobject]@{
        ProfileId = "test-automation-agent"
        BotDisplayName = "Hermes Test Automation Agent"
        HermesCommand = "test-automation-agent"
      }
    )
  }
  [pscustomobject]@{
    Name = "#marketing"
    ApiName = "marketing"
    ChannelId = ""
    InputKey = "slack_channel_marketing"
    Required = $true
    Purpose = "Positioning, messaging, launch planning, and campaign work."
    Bots = @(
      [pscustomobject]@{
        ProfileId = "chief-of-staff"
        BotDisplayName = "Hermes Chief of Staff"
        HermesCommand = "chief-of-staff"
      }
      [pscustomobject]@{
        ProfileId = "marketing-agent"
        BotDisplayName = "Hermes Marketing Agent"
        HermesCommand = "marketing-agent"
      }
    )
  }
  [pscustomobject]@{
    Name = "#qa-review"
    ApiName = "qa-review"
    ChannelId = ""
    InputKey = "slack_channel_qa_review"
    Required = $true
    Purpose = "Risk review, test gaps, contradictions, and assumption checks."
    Bots = @(
      [pscustomobject]@{
        ProfileId = "chief-of-staff"
        BotDisplayName = "Hermes Chief of Staff"
        HermesCommand = "chief-of-staff"
      }
      [pscustomobject]@{
        ProfileId = "qa-critic"
        BotDisplayName = "Hermes QA Critic"
        HermesCommand = "qa-critic"
      }
    )
  }
  [pscustomobject]@{
    Name = "#decisions"
    ApiName = "decisions"
    ChannelId = ""
    InputKey = "slack_channel_decisions"
    Required = $false
    Purpose = "Optional durable decision log and founder decision archive."
    Bots = @(
      [pscustomobject]@{
        ProfileId = "chief-of-staff"
        BotDisplayName = "Hermes Chief of Staff"
        HermesCommand = "chief-of-staff"
      }
      [pscustomobject]@{
        ProfileId = "product-manager"
        BotDisplayName = "Hermes Product Manager"
        HermesCommand = "product-manager"
      }
      [pscustomobject]@{
        ProfileId = "qa-critic"
        BotDisplayName = "Hermes QA Critic"
        HermesCommand = "qa-critic"
      }
    )
  }
  [pscustomobject]@{
    Name = "#alerts"
    ApiName = "alerts"
    ChannelId = ""
    InputKey = "slack_channel_alerts"
    Required = $false
    Purpose = "Optional blockers, failed runs, and urgent operational notices."
    Bots = @(
      [pscustomobject]@{
        ProfileId = "chief-of-staff"
        BotDisplayName = "Hermes Chief of Staff"
        HermesCommand = "chief-of-staff"
      }
    )
  }
)

function Get-LocalSlackToken {
  $token = [Environment]::GetEnvironmentVariable($TokenEnvironmentKey)
  if ([string]::IsNullOrWhiteSpace($token)) {
    throw "Missing local Slack token environment variable: $TokenEnvironmentKey"
  }
  return $token
}

function Invoke-SlackApi {
  param(
    [string]$Method,
    [hashtable]$Body,
    [string]$Token
  )
  $response = Invoke-RestMethod `
    -Uri "https://slack.com/api/$Method" `
    -Method Post `
    -Headers @{ Authorization = "Bearer $Token" } `
    -ContentType "application/json; charset=utf-8" `
    -Body ($Body | ConvertTo-Json -Compress)
  if (-not $response.ok) {
    throw "Slack API $Method failed: $($response.error)"
  }
  return $response
}

function Get-BotUserId {
  param(
    [object]$BotUserMap,
    [string]$ProfileId
  )
  if ($null -eq $BotUserMap) {
    return ""
  }
  $property = $BotUserMap.PSObject.Properties[$ProfileId]
  if ($null -eq $property) {
    return ""
  }
  return [string]$property.Value
}

Write-Host "Slack provisioning runner started."
if (-not $Execute) {
  Write-Host "Dry run only. Add -Execute to call Slack Web API methods."
}
if ($PostDashboardInputs -and -not $Execute) {
  Write-Host "Dashboard input posting is skipped in dry-run mode."
}

$token = ""
if ($Execute) {
  $token = Get-LocalSlackToken
}

function Post-DashboardInput {
  param(
    [string]$Key,
    [string]$Value
  )
  if ([string]::IsNullOrWhiteSpace($Key) -or [string]::IsNullOrWhiteSpace($Value)) {
    return
  }
  $uri = "$DashboardBaseUrl/setup/inputs"
  $body = @{}
  $body[$Key] = $Value
  try {
    Invoke-WebRequest `
      -UseBasicParsing `
      -Method Post `
      -Uri $uri `
      -ContentType "application/x-www-form-urlencoded" `
      -Body $body | Out-Null
    Write-Host "DASHBOARD input $Key=$Value"
  } catch {
    Write-Host "DASHBOARD skipped input ${Key}: $($_.Exception.Message)"
  }
}

if ($CreateChannels) {
  foreach ($channel in $Channels) {
    if (-not [string]::IsNullOrWhiteSpace($channel.ChannelId)) {
      Write-Host "SKIP    $($channel.Name) channel ID already captured"
      continue
    }
    if ($Execute) {
      $response = Invoke-SlackApi `
        -Method "conversations.create" `
        -Token $token `
        -Body @{ name = $channel.ApiName; is_private = $false }
      Write-Host "CREATED $($channel.Name) id=$($response.channel.id)"
      if ($PostDashboardInputs) {
        Post-DashboardInput -Key $channel.InputKey -Value $response.channel.id
      }
    } else {
      Write-Host "CREATE  conversations.create name=$($channel.ApiName)"
    }
  }
}

Write-Host ""
Write-Host "Manual Slack invite commands:"
foreach ($channel in $Channels) {
  Write-Host "[$($channel.Name)]"
  foreach ($bot in $channel.Bots) {
    Write-Host "/invite @$($bot.BotDisplayName)"
  }
}

if ($InviteBots) {
  if (-not (Test-Path -LiteralPath $BotUserMapPath -PathType Leaf)) {
    Write-Host "DEFER  bot user map missing: $BotUserMapPath"
  } else {
    $botUserMap = Get-Content -LiteralPath $BotUserMapPath -Raw | ConvertFrom-Json
    foreach ($channel in $Channels) {
      if ([string]::IsNullOrWhiteSpace($channel.ChannelId)) {
        Write-Host "DEFER  $($channel.Name) channel ID missing"
        continue
      }
      $userIds = @()
      foreach ($bot in $channel.Bots) {
        $userId = Get-BotUserId $botUserMap $bot.ProfileId
        if ([string]::IsNullOrWhiteSpace($userId)) {
          Write-Host "DEFER  $($channel.Name) missing user ID for $($bot.ProfileId)"
        } else {
          $userIds += $userId
        }
      }
      if ($userIds.Count -eq 0) {
        continue
      }
      if ($Execute) {
        Invoke-SlackApi `
          -Method "conversations.invite" `
          -Token $token `
          -Body @{ channel = $channel.ChannelId; users = ($userIds -join ",") } `
          | Out-Null
        Write-Host "INVITED $($channel.Name) users=$($userIds.Count)"
      } else {
        $message = "INVITE  conversations.invite channel=$($channel.ChannelId) "
        $message += "users=$($userIds.Count)"
        Write-Host $message
      }
    }
  }
}

Write-Host "Slack provisioning runner finished. Token values were not printed."
