# Hermes Company OS Telegram provisioning runner
# Generated by the dashboard. Review before running.
# Default mode is dry run. No token values are printed.

param(
  [switch]$CheckBot,
  [switch]$RegisterCommands,
  [switch]$SendTest,
  [switch]$Execute,
  [string]$TokenEnvironmentKey = "HERMES_TELEGRAM_BOT_TOKEN",
  [string]$ChatId = "5916097628",
  [string]$DashboardBaseUrl = "http://127.0.0.1:8002",
  [switch]$PostDashboardStatus
)

$ErrorActionPreference = "Stop"

$Commands = @(
  [pscustomobject]@{
    command = "start"
    description = "Identify the urgent-only Hermes founder alert bot"
  }
  [pscustomobject]@{
    command = "help"
    description = "Show the urgent alert policy and allowed founder commands"
  }
  [pscustomobject]@{
    command = "status"
    description = "Request the latest company operating status"
  }
  [pscustomobject]@{
    command = "approve"
    description = "Record a founder approval for a named decision"
  }
  [pscustomobject]@{
    command = "blocker"
    description = "Escalate a founder-blocking issue to Chief of Staff"
  }
)

function Get-LocalTelegramToken {
  $token = [Environment]::GetEnvironmentVariable($TokenEnvironmentKey)
  if ([string]::IsNullOrWhiteSpace($token)) {
    throw "Missing local Telegram token environment variable: $TokenEnvironmentKey"
  }
  return $token
}

function Invoke-TelegramApi {
  param(
    [string]$Method,
    [hashtable]$Body,
    [string]$Token
  )
  $uri = "https://api.telegram.org/bot$Token/$Method"
  $request = @{
    Uri = $uri
    Method = "Post"
    ContentType = "application/json; charset=utf-8"
  }
  if ($null -ne $Body) {
    $request.Body = $Body | ConvertTo-Json -Depth 8 -Compress
  }
  $response = Invoke-RestMethod @request
  if (-not $response.ok) {
    throw "Telegram Bot API $Method failed"
  }
  return $response
}

Write-Host "Telegram provisioning runner started."
if (-not $Execute) {
  Write-Host "Dry run only. Add -Execute to call Telegram Bot API methods."
}
if ($PostDashboardStatus -and -not $Execute) {
  Write-Host "Dashboard status posting is skipped in dry-run mode."
}

$token = ""
if ($Execute) {
  $token = Get-LocalTelegramToken
}

function Post-TelegramUrgentAlertStatus {
  $uri = "$DashboardBaseUrl/setup/messaging-checks/chief-of-staff-telegram-urgent-alert"
  $body = @{
    status = "verified"
    evidence = "Telegram provisioning runner sent urgent founder alert test."
  }
  try {
    Invoke-WebRequest `
      -UseBasicParsing `
      -Method Post `
      -Uri $uri `
      -ContentType "application/x-www-form-urlencoded" `
      -Body $body | Out-Null
    Write-Host "DASHBOARD verified chief-of-staff-telegram-urgent-alert"
  } catch {
    Write-Host "DASHBOARD skipped chief-of-staff-telegram-urgent-alert: $($_.Exception.Message)"
  }
}

if ($CheckBot) {
  if ($Execute) {
    $response = Invoke-TelegramApi -Method "getMe" -Token $token -Body $null
    Write-Host "CHECKED getMe username=$($response.result.username)"
  } else {
    Write-Host "CHECK   getMe"
  }
}

if ($RegisterCommands) {
  if ($Execute) {
    Invoke-TelegramApi `
      -Method "setMyCommands" `
      -Token $token `
      -Body @{ commands = $Commands } `
      | Out-Null
    Write-Host "COMMANDS registered count=$($Commands.Count)"
  } else {
    Write-Host "COMMANDS setMyCommands count=$($Commands.Count)"
  }
}

if ($SendTest) {
  if ([string]::IsNullOrWhiteSpace($ChatId)) {
    Write-Host "DEFER   ChatId is required for sendMessage"
  } elseif ($Execute) {
    Invoke-TelegramApi `
      -Method "sendMessage" `
      -Token $token `
      -Body @{
        chat_id = $ChatId
        text = "URGENT TEST: Hermes Chief of Staff Telegram alert path is configured."
        disable_web_page_preview = $true
      } `
      | Out-Null
    Write-Host "SENT    sendMessage chat_id=$ChatId"
    if ($PostDashboardStatus) {
      Post-TelegramUrgentAlertStatus
    }
  } else {
    Write-Host "SEND    sendMessage chat_id=$ChatId"
  }
}

if (-not ($CheckBot -or $RegisterCommands -or $SendTest)) {
  Write-Host "Plan:"
  Write-Host "- getMe checks token and bot identity."
  Write-Host "- setMyCommands registers urgent founder commands."
  Write-Host "- sendMessage can send one optional urgent test to the founder/home chat."
}

Write-Host "Telegram provisioning runner finished. Token values were not printed."
