from __future__ import annotations

import json


def first_run_payload() -> dict:
    return {
        "title": "First Run Helper",
        "credential_boundary": (
            "This helper only orchestrates no-secret setup scripts. It does not ask "
            "for, store, print, or post Slack tokens, Telegram bot tokens, provider "
            "API keys, OAuth payloads, profile .env contents, or raw logs."
        ),
        "default_mode": "dry_run_and_safe_prompts",
        "steps": [
            {
                "id": "safe-founder-inputs",
                "label": "Collect safe founder and workspace inputs",
                "route": "/setup/founder-inputs.ps1",
                "default": "prompt only",
                "opt_in_flags": ["-IncludeOptional", "-PostDashboardInputs"],
            },
            {
                "id": "hermes-runtime",
                "label": "Install or connect Hermes runtime",
                "route": "/setup/hermes-install.ps1",
                "default": "print install command only",
                "opt_in_flags": ["-InstallHermes"],
            },
            {
                "id": "runtime-preflight",
                "label": "Inspect runtime and profile readiness",
                "route": "/setup/runtime-preflight.ps1",
                "default": "inspect only",
                "opt_in_flags": ["-FailOnMissing"],
            },
            {
                "id": "activation-runner",
                "label": "Run local profile and provisioning phases",
                "route": "/setup/activation-runner.ps1",
                "default": "skipped",
                "opt_in_flags": ["-RunActivation", "-ActivationArgs"],
            },
        ],
        "entry_points": {
            "script": "/setup/first-run.ps1",
            "markdown": "/setup/first-run.md",
            "json": "/setup/first-run.json",
            "founder_inputs": "/setup/founder-inputs.ps1",
            "hermes_install": "/setup/hermes-install.ps1",
            "runtime_preflight": "/setup/runtime-preflight.ps1",
            "activation_runner": "/setup/activation-runner.ps1",
            "founder_next_actions": "/setup/founder-next-actions.md",
        },
    }


def first_run_json() -> str:
    return json.dumps(first_run_payload(), indent=2, sort_keys=True) + "\n"


def first_run_markdown() -> str:
    payload = first_run_payload()
    lines = [
        "# First Run Helper",
        "",
        "Use this as the local starter command when the dashboard is running but "
        "Hermes runtime, profile assets, and safe founder inputs are not ready yet.",
        "",
        "## Credential Boundary",
        "",
        payload["credential_boundary"],
        "",
        "## Command",
        "",
        "```powershell",
        "Invoke-WebRequest -UseBasicParsing "
        "http://127.0.0.1:8002/setup/first-run.ps1 "
        "-OutFile .\\first-run.ps1",
        ".\\first-run.ps1",
        "```",
        "",
        "## Useful Flags",
        "",
        "- `-IncludeOptional`: include optional safe dashboard inputs.",
        "- `-PostDashboardInputs`: post safe input replies back to this dashboard.",
        "- `-InstallHermes`: run the guarded Hermes install helper with `-RunInstall`.",
        "- `-RunActivation`: download and run `/setup/activation-runner.ps1`.",
        "- `-ActivationArgs`: pass explicit arguments into the activation runner.",
        "",
        "## Steps",
        "",
    ]
    for step in payload["steps"]:
        flags = ", ".join(f"`{flag}`" for flag in step["opt_in_flags"]) or "none"
        lines.extend(
            [
                f"### {step['label']}",
                "",
                f"- Route: `{step['route']}`",
                f"- Default: {step['default']}",
                f"- Opt-in flags: {flags}",
                "",
            ]
        )
    lines.extend(["## Entry Points", ""])
    for label, route in payload["entry_points"].items():
        lines.append(f"- {label}: `{route}`")
    lines.append("")
    return "\n".join(lines)


def first_run_powershell() -> str:
    return """# Hermes Company OS first-run helper
# Generated by the dashboard. No secrets are read, printed, or stored.

param(
  [string]$DashboardBaseUrl = "http://127.0.0.1:8002",
  [switch]$IncludeOptional,
  [switch]$PostDashboardInputs,
  [switch]$InstallHermes,
  [switch]$RunActivation,
  [string[]]$ActivationArgs = @()
)

$ErrorActionPreference = "Stop"

function Save-DashboardScript {
  param(
    [string]$Name,
    [string]$Route
  )
  $scriptPath = Join-Path $env:TEMP "hermes-company-os-$Name.ps1"
  Invoke-WebRequest -UseBasicParsing `
    -Uri "$DashboardBaseUrl$Route" `
    -OutFile $scriptPath
  return $scriptPath
}

function Invoke-Step {
  param(
    [string]$Name,
    [scriptblock]$Action
  )
  Write-Host ""
  Write-Host "==> $Name"
  & $Action
}

Write-Host "Hermes Company OS first-run helper"
Write-Host "Dashboard: $DashboardBaseUrl"
Write-Host "Credential boundary: safe inputs only; no tokens or provider keys."

Invoke-Step "Collect safe founder inputs" {
  $scriptPath = Save-DashboardScript `
    -Name "founder-inputs" `
    -Route "/setup/founder-inputs.ps1"
  $args = @("-DashboardBaseUrl", $DashboardBaseUrl)
  if ($IncludeOptional) { $args += "-IncludeOptional" }
  if ($PostDashboardInputs) { $args += "-PostDashboardInputs" }
  & $scriptPath @args
}

if ($InstallHermes) {
  Invoke-Step "Run guarded Hermes installer" {
    $scriptPath = Save-DashboardScript `
      -Name "hermes-install" `
      -Route "/setup/hermes-install.ps1"
    & $scriptPath -RunInstall
  }
} else {
  Write-Host ""
  Write-Host "Skipping Hermes install. Rerun with -InstallHermes to opt in."
}

Invoke-Step "Run runtime preflight" {
  $scriptPath = Save-DashboardScript `
    -Name "runtime-preflight" `
    -Route "/setup/runtime-preflight.ps1"
  & $scriptPath
}

if ($RunActivation) {
  Invoke-Step "Run activation runner" {
    $scriptPath = Save-DashboardScript `
      -Name "activation-runner" `
      -Route "/setup/activation-runner.ps1"
    $args = @("-DashboardBaseUrl", $DashboardBaseUrl) + @($ActivationArgs)
    & $scriptPath @args
  }
} else {
  Write-Host ""
  Write-Host "Skipping activation runner. Rerun with -RunActivation when ready."
}

Write-Host ""
Write-Host "First-run helper finished."
Write-Host "Review /setup/founder-next-actions.md for the next gate."
"""
