from __future__ import annotations

from hermes_company_os.llm_artifacts import provider_requirements


def llm_finalization_markdown(model_preferences: list[dict]) -> str:
    lines = [
        "# LLM Finalization Runner",
        "",
        "Run this only after profiles, Slack, Telegram, schedules, and Kanban are "
        "ready enough for live smoke checks. It keeps provider credentials last and "
        "never stores API-key values in the dashboard.",
        "",
        "## Command",
        "",
        "```powershell",
        "Invoke-WebRequest -UseBasicParsing "
        "http://127.0.0.1:8002/setup/llm-finalize.ps1 "
        "-OutFile .\\llm-finalize.ps1",
        ".\\llm-finalize.ps1 -PostDashboardStatus",
        ".\\llm-finalize.ps1 -RunModelPicker",
        ".\\llm-finalize.ps1 -RunSmokeChecks",
        "```",
        "",
        "## What It Does",
        "",
        "1. Runs `/setup/secret-audit.ps1 -AuditLlm` to check expected provider key names.",
        "2. Optionally runs `<profile> model` for each profile with `-RunModelPicker`.",
        "3. Optionally calls `/setup/profile-smoke/<profile>` with `-RunSmokeChecks`.",
        "4. Leaves actual provider key values in the real Hermes profile runtime.",
        "",
        "## Profile Matrix",
        "",
    ]
    for preference in model_preferences:
        lines.extend(_profile_lines(preference))
    lines.extend(
        [
            "## Completion Criteria",
            "",
            "- Every LLM credential requirement is marked `loaded` or `verified`.",
            "- Every model preference is `verified` after a dashboard smoke check.",
            "- `/setup#profile-smoke` has one passing run for each profile.",
            "- `llm-provider` integration status is `configured`.",
            "",
            "## Safety",
            "",
            "- Do not paste API-key values into the dashboard.",
            "- Review `/setup/secret-audit.ps1` before using `-PostDashboardStatus`.",
            "- Use `/setup/live-verification.md` after smoke checks pass.",
            "",
        ]
    )
    return "\n".join(lines)


def llm_finalization_powershell(model_preferences: list[dict]) -> str:
    audit_lines = "\n".join(_audit_expectation_line(preference) for preference in model_preferences)
    model_picker_lines = "\n".join(
        f"    {preference['hermes_command']} model" for preference in model_preferences
    )
    smoke_lines = "\n".join(
        f'    Invoke-DashboardPost "/setup/profile-smoke/{preference["agent_id"]}"'
        for preference in model_preferences
    )
    return f"""# Hermes Company OS LLM finalization runner
# Generated by the dashboard. Review before running.
# This script checks key names and triggers smoke checks; it never prints API-key values.

param(
  [string]$DashboardBaseUrl = "http://127.0.0.1:8002",
  [switch]$PostDashboardStatus,
  [switch]$RunModelPicker,
  [switch]$RunSmokeChecks
)

$ErrorActionPreference = "Stop"

function Invoke-Step {{
  param(
    [string]$Name,
    [scriptblock]$Action
  )
  Write-Host ""
  Write-Host "==> $Name"
  & $Action
}}

function Invoke-DashboardPost {{
  param([string]$Path)
  $uri = "$DashboardBaseUrl$Path"
  Invoke-WebRequest -UseBasicParsing -Method Post -Uri $uri | Out-Null
}}

Write-Host "Expected LLM key names by profile:"
{audit_lines}

Invoke-Step "Audit LLM credential key presence" {{
  $auditPath = Join-Path $env:TEMP "hermes-company-os-secret-audit.ps1"
  Invoke-WebRequest -UseBasicParsing `
    -Uri "$DashboardBaseUrl/setup/secret-audit.ps1" `
    -OutFile $auditPath
  if ($PostDashboardStatus) {{
    & $auditPath -DashboardBaseUrl $DashboardBaseUrl -AuditLlm -PostDashboardStatus
  }} else {{
    & $auditPath -DashboardBaseUrl $DashboardBaseUrl -AuditLlm
  }}
}}

if ($RunModelPicker) {{
  Invoke-Step "Run Hermes model picker for each profile" {{
{model_picker_lines}
  }}
}} else {{
  Write-Host "Skipping model picker. Rerun with -RunModelPicker if needed."
}}

if ($RunSmokeChecks) {{
  Invoke-Step "Run dashboard profile smoke checks" {{
{smoke_lines}
  }}
}} else {{
  Write-Host "Skipping profile smoke checks. Rerun with -RunSmokeChecks after keys load."
}}

Write-Host ""
Write-Host "LLM finalization runner finished."
Write-Host "Review /setup#profile-smoke and /setup/readiness-report.md."
"""


def _profile_lines(preference: dict) -> list[str]:
    keys = _profile_keys(preference)
    return [
        f"### {preference['agent_name']}",
        "",
        f"- Profile command: `{preference['hermes_command']}`",
        f"- Provider/model: `{preference['provider']}` / `{preference['model']}`",
        f"- Expected key names: {', '.join(f'`{key}`' for key in keys)}",
        f"- Current status: `{preference['status']}`",
        f"- Smoke route: `/setup/profile-smoke/{preference['agent_id']}`",
        "",
    ]


def _audit_expectation_line(preference: dict) -> str:
    keys = ", ".join(_profile_keys(preference))
    return f'Write-Host "  {preference["agent_id"]}: {keys}"'


def _profile_keys(preference: dict) -> list[str]:
    primary = provider_requirements(preference["provider"])
    keys = list(primary["env"])
    if preference.get("fallback_provider"):
        fallback = provider_requirements(preference["fallback_provider"])
        keys.extend(fallback["env"])
    return list(dict.fromkeys(keys))
