from __future__ import annotations

import json
from collections import Counter

from hermes_company_os.hermes_paths import (
    powershell_hermes_home_param,
    powershell_profile_root_label,
)

IDENTITY_FILES = ["SOUL.md", "capabilities.json", "profile-manifest.json"]
STARTER_FILES = [".env.example", "config.yaml.example"]
LIVE_FILES = [".env", "config.yaml"]


def profile_installation_payload(
    *,
    agents: list[dict],
    profile_installation_checks: list[dict] | None = None,
) -> dict:
    checks = profile_installation_checks or []
    return {
        "title": "Hermes Profile Installation Audit",
        "credential_boundary": (
            "This audit checks profile directories, expected identity files, starter "
            "files, and command aliases only. It does not read, print, store, or "
            "send live `.env` values, provider API keys, Slack tokens, Telegram bot "
            "tokens, OAuth payloads, request headers, private endpoints, or logs."
        ),
        "profile_root": powershell_profile_root_label(),
        "identity_files": IDENTITY_FILES,
        "starter_files": STARTER_FILES,
        "live_files_checked_for_presence_only": LIVE_FILES,
        "profiles": [_profile(agent) for agent in agents],
        "tracking": {
            "status": _status_counts(checks),
            "checks": [_tracking_check(check) for check in checks],
        },
        "entry_points": {
            "bootstrap": "/setup/bootstrap.ps1",
            "profile_artifacts": "/setup/profile-artifacts.md",
            "profile_installation_tracking": "/setup#profile-installation-tracking",
            "runtime_preflight": "/setup/runtime-preflight.md",
            "gateway_operations": "/setup/gateway-operations.md",
            "credential_loading": "/setup/credential-loading.md",
        },
    }


def profile_installation_json(**kwargs) -> str:
    return (
        json.dumps(profile_installation_payload(**kwargs), indent=2, sort_keys=True)
        + "\n"
    )


def profile_installation_markdown(**kwargs) -> str:
    payload = profile_installation_payload(**kwargs)
    lines = [
        "# Hermes Profile Installation Audit",
        "",
        "Use this after running `/setup/bootstrap.ps1` or the per-profile apply scripts.",
        "",
        "## Credential Boundary",
        "",
        payload["credential_boundary"],
        "",
        "## Audit Command",
        "",
        "```powershell",
        "Invoke-WebRequest -UseBasicParsing "
        "http://127.0.0.1:8002/setup/profile-installation.ps1 "
        "-OutFile .\\profile-installation.ps1",
        ".\\profile-installation.ps1",
        "```",
        "",
        "Paste the script output into `/setup#profile-installation-tracking` to "
        "bulk-update profile installation checks without storing file contents.",
        "",
        "## Expected Files",
        "",
        f"- Identity files: {_inline(payload['identity_files'])}",
        f"- Starter files: {_inline(payload['starter_files'])}",
        "- Live files checked only for presence: "
        f"{_inline(payload['live_files_checked_for_presence_only'])}",
        "",
        "## Dashboard Tracking",
        "",
        f"- Status: {_format_counts(payload['tracking']['status'])}",
        "- Update checks at `/setup#profile-installation-tracking`.",
        "",
        "## Profiles",
        "",
    ]
    for profile in payload["profiles"]:
        lines.extend(
            [
                f"### {profile['name']}",
                "",
                f"- Profile ID: `{profile['id']}`",
                f"- Command alias: `{profile['command']}`",
                f"- Profile path: `{profile['profile_path']}`",
                f"- Apply script: `{profile['apply_script']}`",
                f"- Gateway env starter: `{profile['gateway_env']}`",
                f"- LLM env starter: `{profile['llm_env']}`",
                f"- Config starter: `{profile['config']}`",
                "",
            ]
        )
    return "\n".join(lines)


def profile_installation_powershell(agents: list[dict]) -> str:
    profile_block = "\n".join(_profile_powershell(agent) for agent in agents)
    identity_files = _powershell_array(IDENTITY_FILES)
    starter_files = _powershell_array(STARTER_FILES)
    live_files = _powershell_array(LIVE_FILES)
    return f"""# Hermes Company OS profile installation audit
# Generated by the dashboard. Review before running.
# This script checks file presence only. It does not print file contents.

param(
  [string]$HermesHome = {powershell_hermes_home_param()},
  [string]$ProfileRoot = (Join-Path $HermesHome "profiles")
)

$ErrorActionPreference = "Stop"

$Profiles = @(
{profile_block}
)
$IdentityFiles = @({identity_files})
$StarterFiles = @({starter_files})
$LiveFiles = @({live_files})

function Test-CommandAlias {{
  param([string]$CommandLine)
  $commandName = ($CommandLine -split "\\s+")[0]
  return [bool](Get-Command $commandName -ErrorAction SilentlyContinue)
}}

function Write-Check {{
  param(
    [string]$Status,
    [string]$ProfileId,
    [string]$Label
  )
  Write-Host "$Status $ProfileId $Label"
}}

foreach ($profile in $Profiles) {{
  $profilePath = Join-Path $ProfileRoot $profile.Id
  if (Test-Path -LiteralPath $profilePath) {{
    Write-Check "FOUND  " $profile.Id "profile directory"
  }} else {{
    Write-Check "MISSING" $profile.Id "profile directory"
  }}

  if (Test-CommandAlias $profile.Command) {{
    Write-Check "FOUND  " $profile.Id "command alias"
  }} else {{
    Write-Check "MISSING" $profile.Id "command alias"
  }}

  foreach ($fileName in $IdentityFiles) {{
    $filePath = Join-Path $profilePath $fileName
    if (Test-Path -LiteralPath $filePath -PathType Leaf) {{
      Write-Check "FOUND  " $profile.Id $fileName
    }} else {{
      Write-Check "MISSING" $profile.Id $fileName
    }}
  }}

  foreach ($fileName in $StarterFiles) {{
    $filePath = Join-Path $profilePath $fileName
    if (Test-Path -LiteralPath $filePath -PathType Leaf) {{
      Write-Check "FOUND  " $profile.Id $fileName
    }} else {{
      Write-Check "MISSING" $profile.Id $fileName
    }}
  }}

  foreach ($fileName in $LiveFiles) {{
    $filePath = Join-Path $profilePath $fileName
    if (Test-Path -LiteralPath $filePath -PathType Leaf) {{
      Write-Check "FOUND  " $profile.Id "$fileName presence"
    }} else {{
      Write-Check "DEFER  " $profile.Id "$fileName presence"
    }}
  }}
}}

Write-Host ""
Write-Host "Profile installation audit finished. File contents were not printed."
"""


def _profile(agent: dict) -> dict:
    agent_id = agent["id"]
    return {
        "id": agent_id,
        "name": agent["name"],
        "command": agent["hermes_command"],
        "profile_path": f"{powershell_profile_root_label()}\\{agent_id}",
        "apply_script": f"/setup/profile-apply/{agent_id}.ps1",
        "gateway_env": f"/setup/profile-env/{agent_id}.env",
        "llm_env": f"/setup/profile-llm-env/{agent_id}.env",
        "config": f"/setup/profile-config/{agent_id}.yaml",
    }


def _tracking_check(check: dict) -> dict:
    return {
        "id": check["id"],
        "agent_id": check["agent_id"],
        "agent_name": check["agent_name"],
        "label": check["label"],
        "status": check["status"],
        "has_evidence": bool(check.get("evidence", "").strip()),
    }


def _profile_powershell(agent: dict) -> str:
    return f"""  [pscustomobject]@{{
    Id = "{_escape(agent['id'])}"
    Name = "{_escape(agent['name'])}"
    Command = "{_escape(agent['hermes_command'])}"
  }}"""


def _powershell_array(values: list[str]) -> str:
    return ", ".join(f'"{_escape(value)}"' for value in values)


def _inline(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values)


def _status_counts(items: list[dict]) -> dict[str, int]:
    return dict(Counter(item["status"] for item in items))


def _format_counts(counts: dict[str, int]) -> str:
    if not counts:
        return "none"
    return ", ".join(f"{status}={count}" for status, count in sorted(counts.items()))


def _escape(value: str) -> str:
    return value.replace("`", "``").replace('"', '`"')
