from __future__ import annotations

import json
import shutil
import sys
from collections.abc import Callable
from dataclasses import asdict, dataclass
from pathlib import Path

from hermes_company_os.hermes_paths import (
    default_hermes_home,
    powershell_hermes_home_param,
)
from hermes_company_os.settings import Settings


@dataclass(frozen=True)
class RuntimePreflightCheck:
    id: str
    label: str
    status: str
    detail: str
    remediation: str


WhichFn = Callable[[str], str | None]


def runtime_preflight_checks(
    settings: Settings,
    agents: list[dict],
    integrations: list[dict],
    *,
    which: WhichFn = shutil.which,
    home: Path | None = None,
    hermes_home: Path | None = None,
) -> list[RuntimePreflightCheck]:
    resolved_hermes_home = hermes_home or (
        (home / ".hermes") if home is not None else default_hermes_home()
    )
    profile_home = resolved_hermes_home / "profiles"
    database_path = settings.resolved_database_path()
    checks = [
        _python_runtime_check(),
        _poetry_command_check(which),
        _path_check(
            "sqlite-database-directory",
            "SQLite data directory",
            database_path.parent,
            "Run the dashboard once so it can create the local data directory.",
        ),
        _file_check(
            "sqlite-database-file",
            "SQLite database file",
            database_path,
            "Start the dashboard once with `py -3.11 -m poetry run "
            "uvicorn hermes_company_os.main:app --reload`.",
        ),
        _command_check(
            "hermes-cli",
            "Hermes CLI",
            "hermes",
            which,
            "Install Hermes or add the Hermes executable to PATH.",
        ),
    ]
    checks.extend(_profile_checks(agents, profile_home, which))
    checks.extend(_integration_checks(integrations))
    return checks


def runtime_preflight_markdown(checks: list[RuntimePreflightCheck]) -> str:
    summary = _summary(checks)
    lines = [
        "# Runtime Preflight",
        "",
        "Inspect-only checklist for the local Hermes Company OS runtime. It reports "
        "paths, commands, and status metadata only; credentials stay in Hermes "
        "profiles or provider auth flows.",
        "",
        "## Summary",
        "",
        f"- Ready checks: {summary['ready']}",
        f"- Missing checks: {summary['missing']}",
        f"- Deferred checks: {summary['deferred']}",
        f"- Needs setup checks: {summary['needs_setup']}",
        "",
        "## Local Runner",
        "",
        "```powershell",
        "Invoke-WebRequest -UseBasicParsing "
        "http://127.0.0.1:8002/setup/runtime-preflight.ps1 "
        "-OutFile .\\runtime-preflight.ps1",
        ".\\runtime-preflight.ps1",
        ".\\runtime-preflight.ps1 -FailOnMissing",
        "```",
        "",
        "The runner checks local commands and profile paths only. It does not read, "
        "print, or post Slack, Telegram, or provider credential values.",
        "",
        "## Checks",
        "",
    ]
    for check in checks:
        lines.extend(
            [
                f"### {check.label}",
                "",
                f"- Status: `{check.status}`",
                f"- Detail: {check.detail}",
                f"- Next step: {check.remediation}",
                "",
            ]
        )
    lines.extend(
        [
            "## Credential Boundary",
            "",
            "- Do not paste Slack, Telegram, or provider credential values into this file.",
            "- Use `/setup/founder-input-request.md` for non-secret values.",
            "- Use `/setup/live-verification.md` after external credentials are loaded.",
            "",
        ]
    )
    return "\n".join(lines)


def runtime_preflight_json(checks: list[RuntimePreflightCheck]) -> str:
    payload = {
        "title": "Runtime Preflight",
        "credential_boundary": "No secret values are requested or stored by this artifact.",
        "summary": _summary(checks),
        "runner": {
            "route": "/setup/runtime-preflight.ps1",
            "default_mode": "inspect_only",
            "fail_flag": "-FailOnMissing",
        },
        "checks": [asdict(check) for check in checks],
    }
    return json.dumps(payload, indent=2)


def runtime_preflight_powershell(agents: list[dict]) -> str:
    profile_block = "\n".join(_powershell_profile(agent) for agent in agents)
    return f"""# Hermes Company OS runtime preflight runner
# Generated by the dashboard. Inspect-only; no credential values are read or printed.

param(
  [string]$HermesHome = {powershell_hermes_home_param()},
  [string]$ProfileHome = (Join-Path $HermesHome "profiles"),
  [switch]$FailOnMissing
)

$ErrorActionPreference = "Stop"

$Profiles = @(
{profile_block}
)

$Checks = @()

function Add-Check {{
  param(
    [string]$Id,
    [string]$Label,
    [string]$Status,
    [string]$Detail,
    [string]$Remediation
  )
  $script:Checks += [pscustomobject]@{{
    Id = $Id
    Label = $Label
    Status = $Status
    Detail = $Detail
    Remediation = $Remediation
  }}
}}

function Test-CommandReady {{
  param(
    [string]$Id,
    [string]$Label,
    [string]$CommandName,
    [string]$Remediation
  )
  $command = Get-Command $CommandName -ErrorAction SilentlyContinue
  if ($command) {{
    Add-Check $Id $Label "ready" $command.Source $Remediation
  }} else {{
    Add-Check $Id $Label "missing" "`$CommandName was not found on PATH." $Remediation
  }}
}}

function Test-PathReady {{
  param(
    [string]$Id,
    [string]$Label,
    [string]$Path,
    [string]$Remediation
  )
  if (Test-Path -LiteralPath $Path) {{
    Add-Check $Id $Label "ready" $Path $Remediation
  }} else {{
    Add-Check $Id $Label "missing" $Path $Remediation
  }}
}}

Test-CommandReady `
  -Id "poetry-command" `
  -Label "Poetry command" `
  -CommandName "py" `
  -Remediation "Use py -3.11 -m poetry install."

Test-CommandReady `
  -Id "hermes-cli" `
  -Label "Hermes CLI" `
  -CommandName "hermes" `
  -Remediation "Install Hermes or add the Hermes executable to PATH."

Test-PathReady `
  -Id "hermes-profile-home" `
  -Label "Hermes profile home" `
  -Path $ProfileHome `
  -Remediation "Run /setup/bootstrap.ps1 or create profiles with Hermes."

foreach ($profile in $Profiles) {{
  $profilePath = Join-Path $ProfileHome $profile.Id
  Test-PathReady `
    -Id "profile-path-$($profile.Id)" `
    -Label "$($profile.Name) profile directory" `
    -Path $profilePath `
    -Remediation "Run /setup/profile-apply/$($profile.Id).ps1."
  Test-CommandReady `
    -Id "profile-command-$($profile.Id)" `
    -Label "$($profile.Name) command executable" `
    -CommandName $profile.HermesCommand `
    -Remediation "Create or expose the $($profile.HermesCommand) profile alias."
}}

$ready = @($Checks | Where-Object {{ $_.Status -eq "ready" }}).Count
$missing = @($Checks | Where-Object {{ $_.Status -eq "missing" }}).Count

Write-Host "Runtime preflight finished."
Write-Host "Ready checks: $ready"
Write-Host "Missing checks: $missing"
Write-Host ""
foreach ($check in $Checks) {{
  Write-Host "$($check.Status.ToUpper()) $($check.Id) - $($check.Detail)"
}}

if ($FailOnMissing -and $missing -gt 0) {{
  exit 1
}}
"""


def _python_runtime_check() -> RuntimePreflightCheck:
    version = sys.version_info
    ready = version.major == 3 and version.minor >= 11
    return RuntimePreflightCheck(
        id="python-runtime",
        label="Python runtime",
        status="ready" if ready else "missing",
        detail=f"Python {version.major}.{version.minor}.{version.micro}",
        remediation="Use `py -3.11 -m poetry install` before running this app.",
    )


def _poetry_command_check(which: WhichFn) -> RuntimePreflightCheck:
    path = which("py")
    return RuntimePreflightCheck(
        id="poetry-command",
        label="Poetry command",
        status="ready" if path else "missing",
        detail=path or "`py` was not found on PATH. This repo uses `py -3.11 -m poetry`.",
        remediation="Use `py -3.11 -m poetry install`, then run tests through Poetry.",
    )


def _path_check(
    check_id: str,
    label: str,
    path: Path,
    remediation: str,
) -> RuntimePreflightCheck:
    return RuntimePreflightCheck(
        id=check_id,
        label=label,
        status="ready" if path.exists() else "missing",
        detail=str(path),
        remediation=remediation,
    )


def _file_check(
    check_id: str,
    label: str,
    path: Path,
    remediation: str,
) -> RuntimePreflightCheck:
    return RuntimePreflightCheck(
        id=check_id,
        label=label,
        status="ready" if path.is_file() else "missing",
        detail=str(path),
        remediation=remediation,
    )


def _command_check(
    check_id: str,
    label: str,
    command: str,
    which: WhichFn,
    remediation: str,
) -> RuntimePreflightCheck:
    executable = command.split()[0] if command else ""
    path = which(executable) if executable else None
    return RuntimePreflightCheck(
        id=check_id,
        label=label,
        status="ready" if path else "missing",
        detail=path or f"`{executable}` was not found on PATH.",
        remediation=remediation,
    )


def _profile_checks(
    agents: list[dict],
    profile_home: Path,
    which: WhichFn,
) -> list[RuntimePreflightCheck]:
    checks = [
        _path_check(
            "hermes-profile-home",
            "Hermes profile home",
            profile_home,
            "Run `/setup/bootstrap.ps1` or create profiles with Hermes.",
        )
    ]
    for agent in agents:
        profile_path = profile_home / agent["id"]
        checks.append(
            _path_check(
                f"profile-path-{agent['id']}",
                f"{agent['name']} profile directory",
                profile_path,
                f"Run `/setup/profile-apply/{agent['id']}.ps1` or create the profile manually.",
            )
        )
        checks.append(
            _command_check(
                f"profile-command-{agent['id']}",
                f"{agent['name']} command executable",
                agent["hermes_command"],
                which,
                f"Create or expose the `{agent['hermes_command']}` profile alias.",
            )
        )
    return checks


def _integration_checks(integrations: list[dict]) -> list[RuntimePreflightCheck]:
    checks = []
    for integration in integrations:
        status = integration["status"]
        if status in {"configured", "ready"}:
            preflight_status = "ready"
        elif status == "deferred":
            preflight_status = "deferred"
        else:
            preflight_status = "needs_setup"
        checks.append(
            RuntimePreflightCheck(
                id=f"integration-{integration['id']}",
                label=f"{integration['name']} status",
                status=preflight_status,
                detail=f"Dashboard status: `{status}`.",
                remediation=integration["setup_notes"],
            )
        )
    return checks


def _summary(checks: list[RuntimePreflightCheck]) -> dict[str, int]:
    return {
        "ready": len([check for check in checks if check.status == "ready"]),
        "missing": len([check for check in checks if check.status == "missing"]),
        "deferred": len([check for check in checks if check.status == "deferred"]),
        "needs_setup": len([check for check in checks if check.status == "needs_setup"]),
    }


def _powershell_profile(agent: dict) -> str:
    return f"""  [pscustomobject]@{{
    Id = "{_escape(agent['id'])}"
    Name = "{_escape(agent['name'])}"
    HermesCommand = "{_escape(agent['hermes_command'])}"
  }}"""


def _escape(value: str) -> str:
    return value.replace("`", "``").replace('"', '`"')
