from __future__ import annotations

from dataclasses import dataclass

from hermes_company_os.hermes_paths import powershell_hermes_home_param
from hermes_company_os.llm_artifacts import provider_requirements


@dataclass(frozen=True)
class SecretAuditRequirement:
    id: str
    profile_id: str
    category: str
    label: str
    keys: list[str]
    audit_last: bool = False


def secret_audit_requirements(
    secret_requirements: list[dict],
    model_preferences: list[dict],
) -> list[SecretAuditRequirement]:
    model_by_agent = {item["agent_id"]: item for item in model_preferences}
    requirements: list[SecretAuditRequirement] = []
    for item in secret_requirements:
        profile_id = item.get("owner_agent_id")
        if not profile_id:
            continue
        if item["category"] == "llm":
            preference = model_by_agent.get(profile_id)
            keys = _llm_keys(preference) if preference else [item["environment_key"]]
            requirements.append(
                SecretAuditRequirement(
                    id=item["id"],
                    profile_id=profile_id,
                    category=item["category"],
                    label=item["label"],
                    keys=keys,
                    audit_last=True,
                )
            )
            continue
        requirements.append(
            SecretAuditRequirement(
                id=item["id"],
                profile_id=profile_id,
                category=item["category"],
                label=item["label"],
                keys=[item["environment_key"]],
            )
        )
    return requirements


def secret_audit_markdown(requirements: list[SecretAuditRequirement]) -> str:
    messaging = [item for item in requirements if not item.audit_last]
    llm = [item for item in requirements if item.audit_last]
    lines = [
        "# External Secret Audit",
        "",
        "This audit is for after you load credentials into real Hermes profile `.env` "
        "files. It checks only whether required key names exist and are non-empty. "
        "It does not print, store, or send credential values to the dashboard.",
        "",
        "## Commands",
        "",
        "```powershell",
        "Invoke-WebRequest -UseBasicParsing "
        "http://127.0.0.1:8002/setup/secret-audit.ps1 "
        "-OutFile .\\secret-audit.ps1",
        ".\\secret-audit.ps1",
        ".\\secret-audit.ps1 -PostDashboardStatus",
        ".\\secret-audit.ps1 -AuditLlm -PostDashboardStatus",
        "```",
        "",
        "## Default Audit",
        "",
        "The default audit checks Slack and Telegram credentials only. Provider "
        "credentials are intentionally last and require `-AuditLlm`.",
        "",
        "### Messaging Requirements",
        "",
    ]
    lines.extend(_requirement_lines(messaging))
    lines.extend(
        [
            "",
            "### LLM Requirements",
            "",
        ]
    )
    lines.extend(_requirement_lines(llm))
    lines.extend(
        [
            "",
            "## Dashboard Posting",
            "",
            "- `-PostDashboardStatus` marks a requirement `loaded` only when all expected "
            "keys for that requirement are present.",
            "- Missing requirements remain unchanged in the dashboard.",
            "- Notes posted back are generic and contain no credential values.",
            "",
            "## Safety",
            "",
            "- Review the script before running it.",
            "- Keep profile `.env` files outside this repository.",
            "- Use `/setup/live-verification.md` after loaded status is confirmed.",
            "",
        ]
    )
    return "\n".join(lines)


def secret_audit_powershell(requirements: list[SecretAuditRequirement]) -> str:
    requirement_block = "\n".join(
        _requirement_powershell_block(requirement) for requirement in requirements
    )
    return f"""# Hermes Company OS external secret audit
# Generated by the dashboard. Review before running.
# This script checks key presence only; it does not print credential values.

param(
  [string]$DashboardBaseUrl = "http://127.0.0.1:8002",
  [string]$HermesHome = {powershell_hermes_home_param()},
  [string]$ProfileRoot = (Join-Path $HermesHome "profiles"),
  [switch]$PostDashboardStatus,
  [switch]$AuditLlm
)

$ErrorActionPreference = "Stop"

$Requirements = @(
{requirement_block}
)

function Test-ProfileEnvKeys {{
  param(
    [string]$Profile,
    [string[]]$Keys
  )
  $envPath = Join-Path (Join-Path $ProfileRoot $Profile) ".env"
  $loaded = @()
  $missing = @()
  if (-not (Test-Path -LiteralPath $envPath)) {{
    return [pscustomobject]@{{ EnvPath = $envPath; Loaded = $loaded; Missing = $Keys }}
  }}
  $lines = Get-Content -LiteralPath $envPath
  foreach ($key in $Keys) {{
    $found = $false
    foreach ($line in $lines) {{
      $pattern = "^\\s*" + [regex]::Escape($key) + "\\s*=\\s*(.*)$"
      if ($line -match $pattern) {{
        $value = $Matches[1].Trim().Trim('"').Trim("'")
        if ($value -and $value -notmatch "^(REPLACE|TODO|CHANGE_ME|PLACEHOLDER)") {{
          $found = $true
        }}
      }}
    }}
    if ($found) {{
      $loaded += $key
    }} else {{
      $missing += $key
    }}
  }}
  [pscustomobject]@{{ EnvPath = $envPath; Loaded = $loaded; Missing = $missing }}
}}

function Post-LoadedStatus {{
  param([string]$RequirementId)
  $uri = "$DashboardBaseUrl/setup/secret-requirements/$RequirementId"
  $body = @{{
    status = "loaded"
    notes = "Local audit found required key names in the Hermes profile env file."
  }}
  Invoke-WebRequest -UseBasicParsing -Method Post -Uri $uri -Body $body | Out-Null
}}

foreach ($requirement in $Requirements) {{
  if ($requirement.AuditLast -and -not $AuditLlm) {{
    Write-Host "DEFERRED $($requirement.Label) (rerun with -AuditLlm)"
    continue
  }}
  $result = Test-ProfileEnvKeys -Profile $requirement.Profile -Keys $requirement.Keys
  if ($result.Missing.Count -eq 0) {{
    Write-Host "LOADED   $($requirement.Label)"
    if ($PostDashboardStatus) {{
      Post-LoadedStatus -RequirementId $requirement.Id
    }}
  }} else {{
    Write-Host "MISSING  $($requirement.Label): $($result.Missing -join ', ')"
  }}
}}

Write-Host ""
Write-Host "Secret audit finished. Values were not printed or sent to the dashboard."
"""


def _llm_keys(preference: dict | None) -> list[str]:
    if preference is None:
        return ["PROVIDER_API_KEY_OR_OAUTH"]
    primary = provider_requirements(preference["provider"])
    keys = list(primary["env"])
    if preference.get("fallback_provider"):
        fallback = provider_requirements(preference["fallback_provider"])
        keys.extend(fallback["env"])
    return list(dict.fromkeys(keys))


def _requirement_lines(requirements: list[SecretAuditRequirement]) -> list[str]:
    if not requirements:
        return ["- None."]
    lines = []
    for item in requirements:
        keys = ", ".join(f"`{key}`" for key in item.keys)
        lines.append(f"- `{item.profile_id}` {item.label}: {keys}")
    return lines


def _requirement_powershell_block(requirement: SecretAuditRequirement) -> str:
    keys = ", ".join(f'"{_escape(value)}"' for value in requirement.keys)
    audit_last = "$true" if requirement.audit_last else "$false"
    return f"""  [pscustomobject]@{{
    Id = "{_escape(requirement.id)}"
    Profile = "{_escape(requirement.profile_id)}"
    Category = "{_escape(requirement.category)}"
    Label = "{_escape(requirement.label)}"
    Keys = @({keys})
    AuditLast = {audit_last}
  }}"""


def _escape(value: str) -> str:
    return value.replace("`", "``").replace('"', '`"')
